"""Add is_admin column

Revision ID: 78901c040837
Revises: f972e44826da
Create Date: 2024-06-26 18:48:00.829768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78901c040837'
down_revision = 'f972e44826da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
